[package]
name = "sbom"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"]}
serde_json = "1.0"
clap = { version = "4.2", features = ["derive"] }
log = "0.4"
simplelog = "0.10"
serde = "1.0"
serde_derive = "1.0"
csv = "1.1"